FROM registry.access.redhat.com/rhel6.8:latest
MAINTAINER "shihliu@redhat.com"

#Install sam related package
RUN subscription-manager clean
RUN subscription-manager register --username=QualityAssurance --password=VHVFhPS5TEG8dud9 --auto-attach
RUN subscription-manager repos --disable "*"
RUN subscription-manager repos --enable=rhel-6-server-rpms --enable=rhel-6-server-sam-rpms
RUN yum install -y katello-headpin-all

#Config other env
RUN yum install -y openssh-server net-tools hostname sudo
RUN echo "root:red2015" | chpasswd
RUN ssh-keygen -t dsa -f /etc/ssh/ssh_host_dsa_key
RUN ssh-keygen -t rsa -f /etc/ssh/ssh_host_rsa_key

EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]