FROM redhat69:latest
MAINTAINER "shihliu@redhat.com"

RUN yum install -y openssh-server net-tools 
RUN yum install -y hostname sudo passwd
RUN yum install -y subscription-manager
RUN sed -i 's/UsePAM yes/UsePAM no/g' /etc/ssh/sshd_config
RUN echo "root:red2015" | chpasswd
RUN ssh-keygen -t dsa -f /etc/ssh/ssh_host_dsa_key
RUN ssh-keygen -t rsa -f /etc/ssh/ssh_host_rsa_key

VOLUME ["/sys/fs"]
VOLUME ["/run"]
VOLUME ["/export"]

RUN mkdir /var/run/sshd
EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]

