FROM registry.access.redhat.com/rhel7.3:latest
MAINTAINER "shihliu@redhat.com"

#Instll rhevm4.0 package
#RUN setenforce 0
#RUN sed -i -e 's/SELINUX=.*/SELINUX=permissive/g' /etc/sysconfig/selinux
#RUN systemctl stop firewalld
RUN subscription-manager register --username=QualityAssurance --password=VHVFhPS5TEG8dud9 --auto-attach
RUN yum install -y wget
#RUN yum-config-manager --disable rhel-7-server-rt-beta-rpms rhel-7-server-tus-rpms
RUN rpm -Uvh http://bob.eng.lab.tlv.redhat.com/builds/latest_4.1/rhv-release-latest-4.1.noarch.rpm
WORKDIR /etc/yum.repos.d/
RUN wget http://10.66.144.9/home/shihliu/repo/rhevm41.repo
RUN yum install -y rhevm

#Config other env
RUN yum install -y openssh-server net-tools hostname sudo
RUN echo "root:red2015" | chpasswd
RUN ssh-keygen -t dsa -f /etc/ssh/ssh_host_dsa_key
RUN ssh-keygen -t rsa -f /etc/ssh/ssh_host_rsa_key

EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]
