FROM scratch
MAINTAINER "shihliu@redhat.com"

RUN export redhat_root='/redhat_image/rootfs'
RUN mkdir -p $redhat_root
RUN wget http://10.66.144.9/home/shihliu/define.repo
RUN mv define.repo /etc/yum.repos.d
RUN echo $compose_name
RUN sed -i -e 's/'rhelbuild'/'$RHEL_COMPOSE'/g' /etc/yum.repos.d/define.repo
RUN rpm --root $redhat_root --initdb
RUN yum -y reinstall --downloadonly --downloaddir . redhat-release
RUN rpm --root $redhat_root -ivh redhat-release*.rpm
RUN rpm --root $redhat_root --import  $redhat_root/etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release
RUN cp /etc/yum.repos.d/define.repo $redhat_root/etc/yum.repos.d
RUN yum -y --installroot=$redhat_root --setopt=tsflags='nodocs' --setopt=override_install_langs=en_US.UTF-8 install yum
RUN sed -i "/distroverpkg=redhat-release/a override_install_langs=en_US.UTF-8\ntsflags=nodocs" $redhat_root/etc/yum.conf
RUN cp /etc/resolv.conf $redhat_root/etc
RUN chroot $redhat_root /bin/bash yum clean all
RUN tar -C $redhat_root -c . | docker import - $RHEL_IMAGE_NAME

VOLUME ["/sys/fs"]
VOLUME ["/run"]
VOLUME ["/export"]

RUN mkdir /var/run/sshd
EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]

# Register, subscribe and Install packages
RUN subscription-manager register --username=qa@redhat.com --password=uuV4gQrtG7sfMP3q --auto-attach
RUN yum install -y openssh-server net-tools hostname sudo
RUN yum install -y java
RUN yum install -y python-paramiko python-nose
RUN yum install -y python-requests
RUN sed -i 's/UsePAM yes/UsePAM no/g' /etc/ssh/sshd_config
RUN echo "root:red2015" | chpasswd
RUN ssh-keygen -t dsa -f /etc/ssh/ssh_host_dsa_key
RUN ssh-keygen -t rsa -f /etc/ssh/ssh_host_rsa_key
RUN yum install -y wget
RUN yum install -y git

# Update nosetest to make it run with -xunit
RUN rpm -ivh http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm
RUN yum install -y python-pip
RUN yum update python-nose
RUN pip install --upgrade nose
# Update paramiko to make it with esx6.5
RUN yum install -y gcc openssl-devel python-devel
RUN pip install --upgrade pip
RUN pip install --upgrade paramiko

VOLUME ["/sys/fs"]
VOLUME ["/run"]
VOLUME ["/export"]

RUN mkdir /var/run/sshd
EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]

