FROM registry.access.redhat.com/rhel6.8:latest
MAINTAINER "shihliu@redhat.com"

#Instll satellite package
RUN subscription-manager clean
RUN subscription-manager register --username=qa@redhat.com --password=uuV4gQrtG7sfMP3q --auto-attach
#RUN subscription-manager subscribe --pool=8a85f981519abf020151a22d3c387f2a
RUN subscription-manager repos --disable "*"
#RUN subscription-manager repos --enable=rhel-6-server-rpms --enable=rhel-6-server-optional-rpms --enable=rhel-server-rhscl-6-rpms --enable=rhel-6-server-satellite-capsule-6.2-rpms --enable=rhel-6-server-satellite-6.2-rpms --enable=rhel-6-server-satellite-tools-6.2-rpms
RUN subscription-manager repos --enable=rhel-6-server-rpms --enable=rhel-6-server-optional-rpms --enable=rhel-server-rhscl-6-rpms --enable=rhel-6-server-satellite-capsule-6.2-rpms --enable=rhel-6-server-satellite-6.2-rpms --enable=rhel-6-server-satellite-tools-6.2-rpms
RUN subscription-manager repos --enable=rhel-6-server-rpms --enable=rhel-6-server-optional-rpms --enable=rhel-server-rhscl-6-rpms --enable=rhel-6-server-satellite-6.2-rpms --enable=rhel-6-server-satellite-tools-6.2-rpms
RUN yum install -y satellite

#Config other env
RUN yum install -y openssh-server net-tools hostname sudo
RUN echo "root:red2015" | chpasswd
RUN ssh-keygen -t dsa -f /etc/ssh/ssh_host_dsa_key
RUN ssh-keygen -t rsa -f /etc/ssh/ssh_host_rsa_key

EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]