FROM rhel6.8:latest
MAINTAINER "shihliu@redhat.com"


RUN rpm -ivh http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm
RUN yum install -y python-pip
RUN yum update python-nose
RUN pip install --upgrade nose


CMD ["/usr/sbin/sshd", "-D"]

