from utils import *
from testcases.virt_who.virtwhobase import VIRTWHOBase
from utils.exception.failexception import FailException

class tc_ID1015_check_print_function_by_cli(VIRTWHOBase):
    def run_kvm(self):
        try:
            self.runcmd_service("stop_virtwho")
#           (1) Check "DEBUG" info will not exist when run "virt-who --hyperv -p"
            self.config_option_setup_value("VIRTWHO_DEBUG", 0)
            # need to sleep for a second, or else virt-who pid hung up
            cmd = "virt-who -p | sleep 10"
            self.vw_check_message(cmd, "DEBUG", message_exists=False)
#           (2) Check "DEBUG" info is exist when run "virt-who --hyperv -p -d"
            cmd = "virt-who -p -d"
            self.vw_check_message(cmd, "DEBUG")
#           (3) Check jason info is exist in tmp_json.log
            tmp_json = "/tmp/tmp_json.log"
            cmd = "virt-who -p -d > %s" % tmp_json
            json_in_log = self.order_mapping_info(json.loads(self.vw_get_mapping_info(cmd)[0].strip()))
            cmd = "cat %s | python -mjson.tool" % tmp_json
            ret, output = self.runcmd(cmd, "parse json file generated by -p")
            json_printed = self.order_mapping_info(json.loads(output.strip()))
            if json_printed != json_in_log:
                raise FailException("Test Failed - failed to check virt-who print json file compared with json in rhsm.log file")
            else:
                logger.info("Succeeded to check virt-who print json file compared with json in rhsm.log file")
        finally:
            self.config_option_setup_value("VIRTWHO_DEBUG", 1)
            self.runcmd_service("restart_virtwho")
            logger.info("---------- succeed to restore environment ----------")

    def run_vdsm(self):
        try:
            guest_name = self.get_vw_cons("RHEL_RHEVM_GUEST_NAME")
            rhevm_ip = get_exported_param("RHEVM_IP")
            self.runcmd_service("stop_virtwho")

#           (1) Check "DEBUG" info will not exist when run "virt-who --vdsm -p"
            self.config_option_setup_value("VIRTWHO_DEBUG", 0)
            # need to sleep for a second, or else virt-who pid hung up
            cmd = "virt-who --vdsm -p | sleep 10"
            self.vw_check_message(cmd, "DEBUG", message_exists=False)
#           (2) Check "DEBUG" info is exist when run "virt-who --vdsm -p -d"
            cmd = "virt-who --vdsm -p -d"
            self.vw_check_message(cmd, "DEBUG")
#           (3) Check jason info is exist in tmp_json.log
            tmp_json = "/tmp/tmp_json.log"
            cmd = "virt-who --vdsm -p -d > %s" % tmp_json
            json_in_log = self.order_mapping_info(json.loads(self.vw_get_mapping_info(cmd)[0].strip()))
            cmd = "cat %s | python -mjson.tool" % tmp_json
            ret, output = self.runcmd(cmd, "parse json file generated by -p")
            json_printed = self.order_mapping_info(json.loads(output.strip()))
            if json_printed != json_in_log:
                raise FailException("Test Failed - failed to check virt-who print json file compared with json in rhsm.log file")
            else:
                logger.info("Succeeded to check virt-who print json file compared with json in rhsm.log file")
        finally:
            self.config_option_setup_value("VIRTWHO_DEBUG", 1)
            self.runcmd_service("restart_virtwho")
            self.rhevm_stop_vm(guest_name, rhevm_ip)
            logger.info("---------- succeed to restore environment ----------")

    def run_rhevm(self):
        try:
            self.runcmd_service("stop_virtwho")
#           (1) Check "DEBUG" info will not exist when run "virt-who --rhevm -p"
            self.config_option_setup_value("VIRTWHO_DEBUG", 0)
            # need to sleep for a second, or else virt-who pid hung up
            cmd = self.virtwho_cli("rhevm") + " -p | sleep 10"
            self.vw_check_message(cmd, "DEBUG", message_exists=False)
#           (2) Check "DEBUG" info is exist when run "virt-who --rhevm -p -d"
            cmd = self.virtwho_cli("rhevm") + " -p -d"
            self.vw_check_message(cmd, "DEBUG")
#           (3) Check jason info is exist in tmp_json.log
            tmp_json = "/tmp/tmp_json.log"
            cmd = self.virtwho_cli("rhevm") + " -p -d > %s" % tmp_json
            json_in_log = self.order_mapping_info(json.loads(self.vw_get_mapping_info(cmd)[0].strip()))
            cmd = "cat %s | python -mjson.tool" % tmp_json
            ret, output = self.runcmd(cmd, "parse json file generated by -p")
            json_printed = self.order_mapping_info(json.loads(output.strip()))
            if json_printed != json_in_log:
                raise FailException("Test Failed - failed to check virt-who print json file compared with json in rhsm.log file")
            else:
                logger.info("Succeeded to check virt-who print json file compared with json in rhsm.log file")
        finally:
            self.config_option_setup_value("VIRTWHO_DEBUG", 1)
            self.runcmd_service("restart_virtwho")
            logger.info("---------- succeed to restore environment ----------")

    def run_hyperv(self):
        try:
            self.runcmd_service("stop_virtwho")
#           (1) Check "DEBUG" info will not exist when run "virt-who --hyperv -p"
            self.config_option_setup_value("VIRTWHO_DEBUG", 0)
            # need to sleep for a second, or else virt-who pid hung up
            cmd = self.virtwho_cli("hyperv") + " -p | sleep 10"
            self.vw_check_message(cmd, "DEBUG", message_exists=False)
#           (2) Check "DEBUG" info is exist when run "virt-who --hyperv -p -d"
            cmd = self.virtwho_cli("hyperv") + " -p -d"
            self.vw_check_message(cmd, "DEBUG")
#           (3) Check jason info is exist in tmp_json.log
            tmp_json = "/tmp/tmp_json.log"
            cmd = self.virtwho_cli("hyperv") + " -p -d > %s" % tmp_json
            json_in_log = self.order_mapping_info(json.loads(self.vw_get_mapping_info(cmd)[0].strip()))
            cmd = "cat %s | python -mjson.tool" % tmp_json
            ret, output = self.runcmd(cmd, "parse json file generated by -p")
            json_printed = self.order_mapping_info(json.loads(output.strip()))
            if json_printed != json_in_log:
                raise FailException("Test Failed - failed to check virt-who print json file compared with json in rhsm.log file")
            else:
                logger.info("Succeeded to check virt-who print json file compared with json in rhsm.log file")
        finally:
            self.config_option_setup_value("VIRTWHO_DEBUG", 1)
            self.runcmd_service("restart_virtwho")
            logger.info("---------- succeed to restore environment ----------")

    def run_esx(self):
        try:
            self.runcmd_service("stop_virtwho")
            # need to sleep for a second, or else virt-who pid hung up
            cmd = self.virtwho_cli("esx") + " -p | sleep 10"
            self.vw_check_message(cmd, "DEBUG", message_exists=False)
            cmd = self.virtwho_cli("esx") + " -p -d"
            self.vw_check_message(cmd, "DEBUG")
            tmp_json = "/tmp/tmp_json.log"
            cmd = self.virtwho_cli("esx") + " -p -d > %s" % tmp_json
            json_in_log = self.order_mapping_info(json.loads(self.vw_get_mapping_info(cmd)[0].strip()))
            cmd = "cat %s | python -mjson.tool" % tmp_json
            ret, output = self.runcmd(cmd, "parse json file generated by -p")
            json_printed = self.order_mapping_info(json.loads(output.strip()))
            if json_printed != json_in_log:
                raise FailException("Test Failed - failed to check virt-who print json file compared with json in rhsm.log file")
            else:
                logger.info("Succeeded to check virt-who print json file compared with json in rhsm.log file")
        finally:
            logger.info("---------- succeed to restore environment ----------")

    def run_xen(self):
        try:
            self.runcmd_service("stop_virtwho")
#           (1) Check "DEBUG" info will not exist when run "virt-who --hyperv -p"
            self.config_option_setup_value("VIRTWHO_DEBUG", 0)
            # need to sleep for a second, or else virt-who pid hung up
            cmd = self.virtwho_cli("xen") + " -p | sleep 10"
            self.vw_check_message(cmd, "DEBUG", message_exists=False)
#           (2) Check "DEBUG" info is exist when run "virt-who --hyperv -p -d"
            cmd = self.virtwho_cli("xen") + " -p -d"
            self.vw_check_message(cmd, "DEBUG")
#           (3) Check jason info is exist in tmp_json.log
            tmp_json = "/tmp/tmp_json.log"
            cmd = self.virtwho_cli("xen") + " -p -d > %s" % tmp_json
            json_in_log = self.order_mapping_info(json.loads(self.vw_get_mapping_info(cmd)[0].strip()))
            cmd = "cat %s | python -mjson.tool" % tmp_json
            ret, output = self.runcmd(cmd, "parse json file generated by -p")
            json_printed = self.order_mapping_info(json.loads(output.strip()))
            if json_printed != json_in_log:
                raise FailException("Test Failed - failed to check virt-who print json file compared with json in rhsm.log file")
            else:
                logger.info("Succeeded to check virt-who print json file compared with json in rhsm.log file")
        finally:
            self.config_option_setup_value("VIRTWHO_DEBUG", 1)
            self.runcmd_service("restart_virtwho")
            logger.info("---------- succeed to restore environment ----------")

    def test_run(self):
        case_name = self.__class__.__name__
        logger.info("========== Begin of Running Test Case %s ==========" % case_name)
        try:
            hypervisor_type = get_exported_param("HYPERVISOR_TYPE")
            if hasattr(self, "run_" + hypervisor_type):
                getattr(self, "run_" + hypervisor_type)()
            else:
                self.skipTest("test case skiped, not fit for %s" % hypervisor_type)
            self.assert_(True, case_name)
        except Exception, SkipTest:
            logger.info(str(SkipTest))
            raise SkipTest
        except Exception, e:
            logger.error("Test Failed - ERROR Message:" + str(e))
            self.assert_(False, case_name)
        finally:
            logger.info("========== End of Running Test Case: %s ==========" % case_name)

if __name__ == "__main__":
    unittest.main()
