#!/bin/bash
# onboarder daemon
# chkconfig: 345 20 80
# description: onboarder daemon
# processname: onboarder

DAEMON_PATH="/root/ci-message-hub"

DAEMON=onboard.sh
DAEMON_LOG=onboard.log
DAEMONOPTS="-brew -errata -rcm"

NAME=onboarder
DESC="CI message onboarder"
PIDFILE=/var/run/$NAME.pid
SCRIPTNAME=/etc/init.d/$NAME

case "$1" in
start)
        if [ -f $PIDFILE ]; then
            $0 stop
        fi

        /usr/sbin/logrotate -f $DAEMON_PATH/onboard.lconf

	printf "%-50s" "Starting $NAME..."
	PID=`$DAEMON_PATH/$DAEMON $DAEMONOPTS > $DAEMON_PATH/$DAEMON_LOG 2>&1 & echo $!`
        if [ -z $PID ]; then
            printf "%s\n" "Fail"
        else
            echo $PID > $PIDFILE
            printf "%s\n" "Ok"
        fi
;;
status)
        printf "%-50s" "Checking $NAME..."
        if [ -f $PIDFILE ]; then
            PID=`cat $PIDFILE`
            if [ -z "`ps axf | grep ${PID} | grep -v grep`" ]; then
                printf "%s\n" "Process dead but pidfile exists"
            else
                echo "Running"
            fi
        else
            printf "%s\n" "Service not running"
        fi
;;
stop)
        printf "%-50s" "Stopping $NAME"
        PID=`cat $PIDFILE`
        cd $DAEMON_PATH
        if [ -f $PIDFILE ]; then
            pkill -HUP -P $PID
            printf "%s\n" "Ok"
            rm -f $PIDFILE
        else
            printf "%s\n" "pidfile not found"
        fi
;;

restart)
  	$0 stop
  	$0 start
;;

*)
        echo "Usage: $0 {status|start|stop|restart}"
        exit 1
esac
